/**
 * Every value written to audit_logs.action.
 *
 * Kept in one place so the writers and the console's filter dropdown cannot
 * drift apart — the column is a free-form varchar(100), so nothing else would
 * catch a typo.
 */
export const AuditAction = {
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_ROLE_CHANGE: "USER_ROLE_CHANGE",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_REACTIVATE: "USER_REACTIVATE",
  ADMIN_PASSWORD_RESET: "ADMIN_PASSWORD_RESET",
  SESSION_REVOKE: "SESSION_REVOKE",
  SESSIONS_REVOKE_ALL: "SESSIONS_REVOKE_ALL",
  IMPERSONATION_START: "IMPERSONATION_START",
  IMPERSONATION_STOP: "IMPERSONATION_STOP",
  INVOICE_CREATE: "INVOICE_CREATE",
  INVOICE_VOID: "INVOICE_VOID",
  PAYMENT_RECORD: "PAYMENT_RECORD",
  MEDICINE_CREATE: "MEDICINE_CREATE",
  MEDICINE_UPDATE: "MEDICINE_UPDATE",
  MEDICINE_DELETE: "MEDICINE_DELETE",
  BATCH_ADJUST: "BATCH_ADJUST",
  PRESCRIPTION_CREATE: "PRESCRIPTION_CREATE",
  PRESCRIPTION_VERIFY: "PRESCRIPTION_VERIFY",
  PRESCRIPTION_DELETE: "PRESCRIPTION_DELETE",
  INVOICE_RX_ATTACH: "INVOICE_RX_ATTACH",
  PO_CREATE: "PO_CREATE",
  PO_APPROVE: "PO_APPROVE",
  GRN_CREATE: "GRN_CREATE",
  TRANSFER_CREATE: "TRANSFER_CREATE",
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AUDIT_ACTIONS = Object.values(AuditAction);
